spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  profiles:
    active: @bootdemo.enviroment@
  http:
    encoding:
      charset: UTF-8


person:
  name: 马启迪
  age: 18
  accountMap: {1: 100,2: 200}
  departmentNos :
    - 101
    - 102
  department :
    name: market
    departNo: 101

#   test
---
server:
  port: 8080
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zoo?useUnicode=true&amp;autoReconnect=true&amp;characterEncoding=UTF8&amp;allowMultiQueries=true
    dbcp2:
      username: qidi
      password: maqidi4915338
logging:
  file: ./logs/demo.log
  level:
    com.qidi.bootdemo: debug


---


#   dev
server:
  port: 8081
spring:
  profiles: dev
#  日志配置
logging:
  file: ./logs/demo.log
  level:
    com.qidi.bootdemo: trace


---
# prod
server:
  port: 8082
spring:
  profiles: prod
logging:
  file: ./logs/demo.log
  level:
    com.qidi.bootdemo: info



