spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
  datasource:
    first:
      username: "qidi"
      password: "maqidi4915338"
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: "jdbc:mysql://localhost:3306/zoo?useSSL=false"
      connection-timeout: 10000
      maximum-pool-size: 50
      minimum-idle: 100
      idle-timeout: 50000
      connection-test-query: select 1

    second:
      username: "qidi"
      password: "maqidi4915338"
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/zoo2?useSSL=false"
      connection-timeout: 10000
      maximum-pool-size: 50
      minimum-idle: 100
      idle-timeout: 50000
      connection-test-query: select 1


##mybatis 缓存 别名
#mybatis:
#  type-aliases-package: com.qidi.moredatasource.model
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/**/*.xml




---

#   dev
server:
  port: 8080
spring:
  profiles: dev
#  日志配置
logging:
  level:
    com.qidi.bootdemo: debug




